### ISSUE TITLE
TODO list for the Frozen Defense topic

### ISSUE THREAD

**Issue by SmailikHappy** [SmailikHappy/smailikhappy.github.io#1]
Frozen Defense
- [x] Make GIFs / Images / Videos for the post
- [x] Create the repository and the code there
- [x] Create README.md for that repo
