### ISSUE TITLE
TODO for hex jam

### ISSUE THREAD

**Issue by SmailikHappy** [SmailikHappy/smailikhappy.github.io#10]
- [x] create a repo / distributive for the game code
- [x] create a post on the website
- [x] put some media on it
