### ISSUE TITLE
TODO list for the Discord bot topic 

### ISSUE THREAD

**Issue by SmailikHappy** [SmailikHappy/smailikhappy.github.io#6]
- [X] ~~create repo and put code of the bot there~~
- [x] README.md of course
- [x] add some images / gifs / videos
