### ISSUE TITLE
TODO list for the home page

### ISSUE THREAD

**Issue by SmailikHappy** [SmailikHappy/smailikhappy.github.io#8]
- [x] write some more information to the home page
- [x] fix the alignment issues
- [x] make a nice photo of myself
- [x] Fix the top text for mobile devices
